### ISSUE TITLE
Stability Issues when repeating tests several times

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/zeebe-process-test#122] opened 2021-12-22 10:13 UTC
## Description
When repeating tests several times: (e.g. Idea "Repeat until failure" mode) the tests exhibit the following behavior:
* Memory grows 
* Threadcount grows
* At some point the tests just stop.

### Expected behaviour
Memory stays constant, thread count stays constant, tests can run forever

## Reproduction steps
* Intellij Idea
* Select test folder
* Right click + "Modify Run Configuration"
* "Modify options" > "Tests" > "Repeat" > "Until Failure"
* Wait

<details>
<summary>Log Excerpt</summary>

When it gets stuck, it is usually at this position:
```
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.processor - Processor starts replay of events. [snapshot-position: -1, replay-mode: PROCESSING]
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.processor - Processor finished replay at event position -1
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.engine.state.migration - Starting processing of migration tasks (use LogLevel.DEBUG for more details) ... 
11:05:09.799 [-zb-actors-20] DEBUG io.camunda.zeebe.engine.state.migration - Found 3 migration tasks: ProcessMessageSubscriptionSentTimeMigration, MessageSubscriptionSentTimeMigration, TemporaryVariableMigration
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.engine.state.migration - Skipping ProcessMessageSubscriptionSentTimeMigration migration (1/3).  It was determined it does not need to run right now.
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.engine.state.migration - Skipping MessageSubscriptionSentTimeMigration migration (2/3).  It was determined it does not need to run right now.
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.engine.state.migration - Skipping TemporaryVariableMigration migration (3/3).  It was determined it does not need to run right now.
11:05:09.799 [-zb-actors-20] INFO  io.camunda.zeebe.engine.state.migration - Completed processing of migration tasks (use LogLevel.DEBUG for more details) ... 
11:05:09.799 [-zb-actors-20] DEBUG io.camunda.zeebe.engine.state.migration - Executed 0 migration tasks: 
```

</details>

Memory and Thread Leak:
![image](https://user-images.githubusercontent.com/14032870/147076066-83907dc6-4a04-4e65-9196-ae7a47f52f63.png)

Threads which are leaking:
![image](https://user-images.githubusercontent.com/14032870/147076289-f643206d-264f-46fa-9ac5-ca30c73f0a1d.png)

**Comment by pihme** [comment] 2021-12-22 12:36
Thread dump of moment in time when execution is stuck (unfortunately too many threads due to thread leak)

[threaddump.tar.gz](https://github.com/camunda-cloud/zeebe-process-test/files/7762637/threaddump.tar.gz)

**Comment by pihme** [comment] 2021-12-22 13:31
Braindump of my investigations so far:
There seems to be an issue with the dynamic sockets and running all tests multiple times in a row.
There is a pair of `addServer/removeServer` methods in `InternalChannelz`

Usually this works as expected and the list of servers is 1 and reduced to 0 after the test.

However, when running all tests in a loop, for each loop of the full test suite, one server gets left in the list and apparently accumulates. 

![image](https://user-images.githubusercontent.com/14032870/147100250-dac2668b-2fac-4cb6-b327-1f71289102cb.png)

Note that this did not happen when running a single test class in a loop. The offset is always +1. So it tries to remove the server with the port 1 higher than the highest port of all the servers in the list.

**Comment by pihme** [comment] 2021-12-22 14:28
Bit of a summary:

**Memory Leak**
* caused by us not cleaning up the `ExtensionContext.Store` after a test. The commit https://github.com/camunda-cloud/zeebe-process-test/commit/ac0e028ceca1cd58c867d67b3b07a3b575920ea0 is the right idea and fixes the memory leak. However, it removes the objects too early. They are no longer available in the `testFailed()` method. Maybe exploring #123 could help here. But basically it's a problem of the lifecycle and releasing references after a test
* Also caused by thread leak (see next)

**Thread Leak**
* Happens in `ZeebeProcessTestExtensionTest`. In this test we create a test engine (which spawns threads) but we don't clean it up properly
* The commit https://github.com/camunda-cloud/zeebe-process-test/commit/c5d3616b244ca36a5a0d17ae8e89a5bebd5861f8 is also helpful. In my tests it reduced the number of GC roots to `ActorScheduler` However, it could be that this commit is no longer necessary if the root cause is fixed

**Tests randomly stopping**
No idea yet. I want to get the thread count low, before investigating this further.

**Comment by remcowesterhoud** [comment] 2022-01-12 15:22
I've sort of found the cause of the hanging tests. I'm not sure why it happens, but this is what I found:

It has to do with the `IdleStateMonitor`. In this class we have an `idleStateNotifier`, which is used for triggering the callbacks that get registered via the `InMemoryEngine` when it wait for an idle state.

When we check for an idle state there is 2 possible scenarios. We either are in an idle state, or we are not. If we are in an idle state we will schedule the `idleStateNotifier` which in turn run the callbacks. If we are not in an idle state we will cancel the `idleStateNotifier`.

```java
  private void checkIdleState() {
    if (isInIdleState()) {
      scheduleNotification();
    } else {
      cancelNotification();
    }
  }

  private void scheduleNotification() {
    synchronized (idleStateNotifier) {
      idleStateNotifier = createIdleStateNotifier();
      try {
        TIMER.schedule(idleStateNotifier, GRACE_PERIOD);
      } catch (IllegalStateException e) {
        // thrown - among others - if task was cancelled before it could be scheduled
        // do nothing in this case
      }
    }
  }

  private void cancelNotification() {
    synchronized (idleStateNotifier) {
      idleStateNotifier.cancel();
    }
  }
```


The issue seems to be resolved by combining these 2 `synchronized` into 1 (I've ran tens of thousands of tests with this change without getting stuck):
```java
  private void checkIdleState() {
    synchronized (idleStateNotifier) {
      if (isInIdleState()) {
        scheduleNotification();
      } else {
        cancelNotification();
      }
    }
  }

  private void scheduleNotification() {
    idleStateNotifier = createIdleStateNotifier();
    try {
      TIMER.schedule(idleStateNotifier, GRACE_PERIOD);
    } catch (IllegalStateException e) {
      // thrown - among others - if task was cancelled before it could be scheduled
      // do nothing in this case
    }
  }

  private void cancelNotification() {
    idleStateNotifier.cancel();
  }
```

I'll create a PR with this fix later on, but I'm interested to know why the current solution is causing issues. Any idea @pihme?

**Comment by pihme** [comment] 2022-01-12 15:38
Not sure to be honest. Off the top of my head I wonder if it could be due to the answer to `isInIdleState` becoming incorrect while we wait to acquire a lock :thinking:

**Closed** 2022-01-12 15:39 UTC
Labels: Type: Bug
